mv main.c main_bonus.c
mv render.c render_bonus.c
mv cast_hz.c cast_hz_bonus.c
mv cast_vt.c cast_vt_bonus.c
mv cast_ray.c cast_ray_bonus.c 
mv utils.c utils_bonus.c
mv key_events.c key_events_bonus.c 
mv player.c player_bonus.c
mv texture.c texture_bonus.c
mv grid.c grid_bonus.c 
mv images.c images_bonus.c 
mv window.c window_bonus.c
mv utils_init.c window.c_bonus.c 
mv utils_render.c utils_render_bonus.c
mv error.c error_bonus.c
mv parsers/parse_input.c parsers/parse_input_bonus.c
mv parsers/map/check_borders.c parsers/map/check_borders_bonus.c 
mv parsers/map/check_walls.c parsers/map/check_walls_bonus.c 
mv parsers/map/parse_map.c parsers/map/parse_map_bonus.c
mv parsers/map/parse_map2.c parsers/map/parse_map2_bonus.c
mv parsers/parameters/parse_line_paths.c parsers/parameters/parse_line_paths_bonus.c
mv parsers/parameters/check_open_file.c parsers/parameters/check_open_file_bonus.c
mv utils/append_error.c utils/append_error_bonus.c
mv utils/detect_line_map.c utils/detect_line_map_bonus.c
mv utils/ft_is_number.c utils/ft_is_number_bonus.c
mv utils/is_in_charset.c utils/is_in_charset_bonus.c 
mv utils/number_of_args.c utils/number_of_args_bonus.c 
mv list_map.c list_map_bonus.c 
mv utils/preli.c utils/preli_bonus.c
mv render_2d.c render_2d_bonus.c
